apiVersion: v1
kind: Service
metadata:
  name: test # the name of our service
spec:
  type: LoadBalancer
  selector:
    app: test # pods are deployed with the label app=SearchApp
  ports:
    - port: 80